# Generated by Django 5.0 on 2023-12-19 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_original_bag_order_stripe_pid_and_more'),
        ('products', '0002_alter_category_options_product_has_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_order_line_items', to='products.product'),
        ),
    ]
